import os
import xml.etree.ElementTree as ET
import sys, re

def indent(elem, level=0, sp="  "):
    i = "\n" + level*sp
    if len(elem):
        if not (elem.text or "").strip(): elem.text = i + sp
        for c in elem: indent(c, level+1, sp)
        if not (c.tail or "").strip(): c.tail = i
    if level and not (elem.tail or "").strip(): elem.tail = i

def convert(src, macro_name, out, mesh_dir):
    root = ET.parse(src).getroot()
    body = []
    for el in root:
        if el.tag == "link":
            el.set("name", el.get("name") + "${suffix}")
            # Vendor the meshes: this package ships its own copy so the repo
            # clones and runs without left_arm_description / right_arm_description.
            for mesh in el.iter("mesh"):
                fn = mesh.get("filename")
                mesh.set("filename",
                         "package://dhl_description/meshes/%s/%s" % (mesh_dir, fn.rsplit("/", 1)[1]))
            for mat in el.iter("material"):
                mat.set("name", "dhl_light")
                for c in list(mat.findall("color")): mat.remove(c)
        elif el.tag == "joint":
            el.set("name", el.get("name") + "${suffix}")
            for tag in ("parent", "child"):
                n = el.find(tag)
                n.set("link", n.get("link") + "${suffix}")
            # exported effort/velocity are 0; fill placeholders so the model is usable
            lim = el.find("limit")
            if lim is not None:
                if float(lim.get("effort", 0)) == 0.0:   lim.set("effort", "${arm_effort}")
                if float(lim.get("velocity", 0)) == 0.0: lim.set("velocity", "${arm_velocity}")
        else:
            continue
        indent(el, 2)
        body.append(ET.tostring(el, encoding="unicode"))

    with open(out, "w") as f:
        f.write('<?xml version="1.0"?>\n')
        f.write(f'<!-- AUTO-GENERATED by gen_arm_macro.py from {src} - do not edit by hand.\n')
        f.write('     7-DOF arm (j1..j7). Link/joint names get ${suffix} appended.\n')
        f.write('     Mesh paths point at this package own copy under meshes/. -->\n')
        f.write('<robot xmlns:xacro="http://www.ros.org/wiki/xacro">\n\n')
        f.write(f'  <xacro:macro name="{macro_name}" params="suffix parent *origin">\n\n')
        f.write('    <joint name="arm_mount${suffix}" type="fixed">\n')
        f.write('      <xacro:insert_block name="origin" />\n')
        f.write('      <parent link="${parent}" />\n')
        f.write('      <child link="base_link${suffix}" />\n')
        f.write('    </joint>\n')
        f.write("    " + "".join(body).strip() + "\n\n")
        f.write('  </xacro:macro>\n\n</robot>\n')
    print(f"wrote {out}")

# .../src/<whatever>/ - the folder holding this package and the two arm exports
base = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
convert(f"{base}/left_arm_description/urdf/left_arm_description.urdf",
        "arm7_left", f"{base}/dhl_description/urdf/arm7_left.xacro", "left_arm")
convert(f"{base}/right_arm_description/urdf/right_arm_description.urdf",
        "arm7_right", f"{base}/dhl_description/urdf/arm7_right.xacro", "right_arm")
